# See: https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["bin/*", "lib/*"]
default-members = ["bin/*", "lib/*"]
resolver = "2"

[workspace.package]
version = "0.2.1"
authors = ["Arto Bendiken"]
edition = "2021"
rust-version = "1.81"
description = "RDF.rs is a Rust framework for working with RDF knowledge graphs."
#documentation = "https://docs.rs/rdf-model/"
readme = true
homepage = "https://github.com/rust-rdf"
repository = "https://github.com/rust-rdf/rdf.rs"
license = "Unlicense"
keywords = ["rdf", "knowledge-graph", "linked-data", "semantic-web"]
categories = ["data-structures", "no-std"]
publish = true

[workspace.dependencies]
dogma = { version = "0.1", default-features = false, features = ["traits"] }
rdf_rs = { version = "=0.2.1", default-features = true }
rdf-borsh = { version = "=0.2.1", default-features = true }
rdf-derive = { version = "=0.2.1", default-features = true }
rdf-format = { version = "=0.2.1", default-features = true }
rdf-model = { version = "=0.2.1", default-features = true }
rdf-query = { version = "=0.2.1", default-features = true }
rdf-reader = { version = "=0.2.1", default-features = true }
rdf-vocab = { version = "=0.2.1", default-features = true }
rdf-writer = { version = "=0.2.1", default-features = true }

[patch.crates-io]
rdf-cli = { path = "bin/rdf" }
rdf_rs = { path = "lib/rdf_rs" }
rdf-borsh = { path = "lib/rdf-borsh" }
rdf-derive = { path = "lib/rdf-derive" }
rdf-format = { path = "lib/rdf-format" }
rdf-model = { path = "lib/rdf-model" }
rdf-query = { path = "lib/rdf-query" }
rdf-reader = { path = "lib/rdf-reader" }
rdf-vocab = { path = "lib/rdf-vocab" }
rdf-writer = { path = "lib/rdf-writer" }
